Callback.pm version needs to follow API.pm
Or you get error messages like:

Error:  Win32::API::Callback object version 0.66
  does not match $Win32::API::Callback::VERSION 0.65 at ...